In [1]:
import numpy as np
import pandas as pd

In [2]:
dados_covid = pd.read_csv("./COVID19.csv")
# para maiores informações sobre este conjunto de dados acessar:
# https://ourworldindata.org/coronavirus

In [3]:
dados_covid.head(5)

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,AFG,Asia,Afghanistan,24/02/2020,5,5,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
1,AFG,Asia,Afghanistan,25/02/2020,5,0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
2,AFG,Asia,Afghanistan,26/02/2020,5,0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
3,AFG,Asia,Afghanistan,27/02/2020,5,0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
4,AFG,Asia,Afghanistan,28/02/2020,5,0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN

In [4]:
dados_covid = pd.read_csv("./COVID19.csv")
dados_covid = dados_covid[['iso_code','continent','location','date','total_cases','new_cases']]

In [5]:
dados_covid

     iso_code continent     location        date  total_cases  new_cases
0         AFG      Asia  Afghanistan  24/02/2020            5          5
1         AFG      Asia  Afghanistan  25/02/2020            5          0
2         AFG      Asia  Afghanistan  26/02/2020            5          0
3         AFG      Asia  Afghanistan  27/02/2020            5          0
4         AFG      Asia  Afghanistan  28/02/2020            5          0
...       ...       ...          ...         ...          ...        ...
5813      NGA    Africa      Nigeria  06/10/2022       265741        236
5814      NGA    Africa      Nigeria  07/10/2022       265741          0
5815      NGA    Africa      Nigeria  08/10/2022       265816         75
5816      NGA    Africa      Nigeria  09/10/2022       265816          0
5817      NGA    Africa      Nigeria  10/10/2022       265816          0

[5818 rows x 6 columns]

In [6]:
dados_covid.dtypes

iso_code         str
continent        str
location         str
date             str
total_cases    int64
new_cases      int64
dtype: object

In [7]:
dados_covid.shape

(5818, 6)

In [8]:
# Métricas de Tendência Central

In [9]:
média_dos_dados = np.mean(dados_covid["new_cases"])
média_dos_dados

np.float64(8814.365761430045)

In [10]:
média_dos_dados = dados_covid["new_cases"].mean()
média_dos_dados

np.float64(8814.365761430045)

In [11]:
mediana_dados = np.median(dados_covid["new_cases"])

In [12]:
mediana_dados

np.float64(261.0)

In [13]:
mediana_dos_dados = dados_covid["new_cases"].median()
mediana_dos_dados

np.float64(261.0)

In [14]:
import scipy
print(scipy.__version__)

1.17.1

In [15]:
from scipy import stats

In [16]:
moda_dados = stats.mode(dados_covid["new_cases"])

In [17]:
moda_dados

ModeResult(mode=np.int64(0), count=np.int64(805))

In [18]:
moda_dados[0]

np.int64(0)

In [19]:
# Métricas de Dispersão dos Dados

In [20]:
variancia_dados = np.var(dados_covid["new_cases"])
variancia_dados

np.float64(451321915.9280954)

In [21]:
dados_covid["new_cases"].var()

np.float64(451399502.6421969)

In [22]:
sd_dados = np.std(dados_covid["new_cases"])
sd_dados

np.float64(21244.338444114834)

In [23]:
dados_covid["new_cases"].std()

np.float64(21246.164421895)

In [24]:
max_dados = np.max(dados_covid["new_cases"])
min_dados = np.min(dados_covid["new_cases"])

In [25]:
print(max_dados, min_dados)

287149 0

In [26]:
max_dados = dados_covid["new_cases"].max()
min_dados = dados_covid["new_cases"].min()

In [27]:
max_dados

np.int64(287149)

In [28]:
min_dados

np.int64(0)

In [29]:
faixa_dados = max_dados - min_dados
faixa_dados

np.int64(287149)

In [30]:
percentil_dados = np.percentile(dados_covid["new_cases"],60)
percentil_dados

np.float64(591.3999999999996)

In [31]:
quartil_dados = np.quantile(dados_covid["new_cases"],0.75)
quartil_dados

np.float64(3666.0)

In [32]:
IQR_dados = stats.iqr(dados_covid["new_cases"], interpolation = 'midpoint')
IQR_dados

np.float64(3641.0)

In [33]:
IQR_dados = stats.iqr(dados_covid["new_cases"])
IQR_dados

np.float64(3642.0)

In [34]:
# deverão pesquisar o motivo do IQR dar diferente entre as duas versões anteriores
# sugiro verificar o help de cada função