LAB05 - Tarefa 02

vamos implementar um agrupamento k-means com várias métricas apenas como comparação com os outros modelos deste laboratório. Abrir o ambiente de programação Python e digitar o código disponibilizado abaixo. Nesta tarefa, vamos analisar e rodar o código do arquivo Lab04Tarefa02 disponibilizado na nossa Comunidade da disciplina no Moodle.

In [1]:
# Importa as bibliotecas necessárias e a base de dados "diabetes"
import pandas as pd

In [2]:
diabetes = pd.read_csv("./diabetes.csv")
diabetes.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [3]:
conj_caract = ['Pregnancies','Insulin','BMI','Age','Glucose','BloodPressure','DiabetesPedigreeFunction']
caracts = diabetes[conj_caract]
caracts = (caracts - caracts.min())/(caracts.max()-caracts.min())
alvo = diabetes.Outcome
caracts.head()

,Pregnancies,Insulin,BMI,Age,Glucose,BloodPressure,DiabetesPedigreeFunction
0,0.352941,0.000000,0.500745,0.483333,0.743719,0.590164,0.234415
1,0.058824,0.000000,0.396423,0.166667,0.427136,0.540984,0.116567
2,0.470588,0.000000,0.347243,0.183333,0.919598,0.524590,0.253629
3,0.058824,0.111111,0.418778,0.000000,0.447236,0.540984,0.038002
4,0.000000,0.198582,0.642325,0.200000,0.688442,0.327869,0.943638

In [4]:
# Aplica o método k-means para separar em dois agrupamentos e testa várias métricas de desempenho

from sklearn.model_selection import train_test_split
caract_trein, caract_teste, alvo_trein, alvo_teste = train_test_split(caracts, alvo,test_size=0.3, random_state=1)

from sklearn.cluster import KMeans
from sklearn.metrics import davies_bouldin_score
from sklearn.metrics import silhouette_score
from sklearn.metrics import adjusted_rand_score
from sklearn.metrics import jaccard_score
from sklearn.metrics import f1_score
from sklearn.metrics import fowlkes_mallows_score
num_clusters = 2
km = KMeans(n_clusters=num_clusters)
km.fit(caract_trein)
predicoes=km.predict(caract_teste)
print("Índice Davies-Bouldin:", davies_bouldin_score(caract_teste, predicoes))
print("Coeficiente da Silhueta:", silhouette_score(caract_teste, predicoes))
print("Adjusted Rand Score:", adjusted_rand_score(alvo_teste, predicoes))
print("F1-Score:", f1_score(alvo_teste, predicoes))
print("Escore Fowlkes Mallows:", fowlkes_mallows_score(alvo_teste, predicoes))

Índice Davies-Bouldin: 1.4348787674830534
Coeficiente da Silhueta: 0.2834758484814906
Adjusted Rand Score: 0.12644442464567127
F1-Score: 0.3305084745762712
Escore Fowlkes Mallows: 0.5973161888113763